services:
  frontend:
    # Dockerfileがある場所を指定
    build: ./frontend
    container_name: frontend-container
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/backend
    tty: true
    stdin_open: true
  # web:
  #   image: nginx:1.25.1-alpine-slim
  #   container_name: nginx-container
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./frontend:/frontend
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    env_file:
      - ./backend/src/.env
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    env_file:
      - ./backend/src/.env
    ports:
      - "3001:80"
volumes:
  mysql:
    driver: local
  node_modules:
